#!/bin/sh
#
# Start ai service.
#

if [ "$(id -u)" -eq 0 ]; then
      su -c "$0 $@" creality
      exit 0
fi

USER_DATA=/usr/data
PROG=/usr/apps/usr/bin/solusp
SYS_CONFIG_DIR=/etc/appetc/solusp
USER_CONFIG_DIR=/usr/data/creality/solusp
PRINTER_DATA_DIR=$USER_DATA/printer_data
PRINTER_LOGS_DIR=$PRINTER_DATA_DIR/logs/
PID_FILE=/home/creality/run/solusp.pid

start() {
      [ -d $PRINTER_DATA_DIR ] || mkdir -p $PRINTER_DATA_DIR
      [ -d $PRINTER_LOGS_DIR ] || mkdir -p $PRINTER_LOGS_DIR
      [ -d $USER_CONFIG_DIR ] || mkdir -p $USER_CONFIG_DIR
      [ -d $USER_CONFIG_DIR/template ] || cp -rf $SYS_CONFIG_DIR/template $USER_CONFIG_DIR

      HOME=/root start-stop-daemon -S -q -b -m -p $PID_FILE \
            --exec $PROG -- -k=/tmp/klippy_uds -l=$PRINTER_LOGS_DIR/solusp.log -s=$SYS_CONFIG_DIR/ -u=$USER_CONFIG_DIR/
}
stop() {
        start-stop-daemon -K -q -p $PID_FILE
}
restart() {
        stop
        start
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        restart
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
