#!/bin/sh
#
# Start onyxp service.
#

if [ "$(id -u)" -eq 0 ]; then
      su -c "$0 $@" creality
      exit 0
fi

USER_DATA=/usr/data
CONFIG_DIR=/etc/appetc/onyxp
PROG=/usr/apps/usr/bin/onyxp

PRINTER_DATA_DIR=$USER_DATA/printer_data
PRINTER_LOGS_DIR=$PRINTER_DATA_DIR/logs/
PID_FILE=/home/creality/run/onyxp.pid

start() {
      [ -d $PRINTER_DATA_DIR ] || mkdir -p $PRINTER_DATA_DIR
      [ -d $PRINTER_LOGS_DIR ] || mkdir -p $PRINTER_LOGS_DIR

      HOME=/root start-stop-daemon -S -q -b -m -p $PID_FILE \
            --exec $PROG -- -c $CONFIG_DIR/onyxp.json
}
stop() {
        start-stop-daemon -K -q -p $PID_FILE
}
restart() {
        stop
        sleep 1.5
        start
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        restart
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
