#! /bin/sh

if [ "$(id -u)" -ne 0 ]; then
      echo "$0: Operation permission not permitted"
      exit 1
fi

case "$1" in
  start)
    [ -f /usr/data/printer_data/logs/kernel.log ] && mv /usr/data/printer_data/logs/kernel.log /usr/data/printer_data/logs/kernel.log.bak
    cat /proc/kmsg | sed "/AICWFDBG\|get_txpwr_max/d" > /usr/data/printer_data/logs/kernel.log &
    ;;
  stop)
    ;;
  restart|reload)
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|reload}" >&2
    exit 1
    ;;
esac

exit 0

