#!/bin/sh
# ==========================================================================
#  reapply.sh  —  one-command restore of the live Cartographer setup on the
#  2025 Creality K1C / K1 Max (Ingenic X2600, firmware K1C-2025_V1.0.0.x)
#
#  WHY THIS EXISTS
#  A NORMAL REBOOT needs nothing from this script. Everything persists:
#  the plugin + scipy shim + wsshim/fluidd libs on /usr/data (p10), your
#  printer_data config on /usr/data, AND the klippy extras + boot hooks that
#  install.sh writes into /usr/apps — which on the real 2025 board is a
#  WRITABLE ext4 partition (p8), so those files stay across power cycles.
#
#  The one event that wipes them is a Creality FIRMWARE UPDATE / re-seed: it
#  rewrites the /usr/apps partition from the new image and destroys:
#      * the klippy extras: cartographer.py scaffold, carto_prtouch_shim.py,
#        carto_shell_command.py
#      * the boot hooks: /usr/apps/etc/init.d/S97dbshim, S98fluidd
#  (a re-seed can also reset printer.cfg via CS55klipper_service). After a
#  firmware update those have to be laid back down. That is what this script
#  automates, OFFLINE — no pip, no internet.
#
#  It NEVER touches the bootloader, kernel, or any secure-boot / SCBT
#  partition. It only rewrites files under /usr/apps and (idempotently) adds
#  include lines to printer.cfg after backing it up.
#
#  FIRST TIME (needs internet, once):    sh install.sh  [+ wsshim/fluidd installers]
#  AFTER A FIRMWARE UPDATE / RE-SEED:    sh reapply.sh
#  AFTER A PLAIN REBOOT:                 nothing — it all persists
#
#  Keep this whole repo directory on the printer under /usr/data so it too
#  survives a re-seed, e.g.  /usr/data/k1-2025-cartographer , and run it from
#  there.  Run ON the printer, as root.
# ==========================================================================
set -eu

# --- resolve where this script (and its extras/ config/) lives ------------
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# --- paths (must match install.sh) ----------------------------------------
LIB_DIR="/usr/data/cartographer/lib"
PKG_PARENT="/usr/data/cartographer"
KLIPPER_DIR="/usr/apps/usr/share/klipper"
EXTRAS_DIR="${KLIPPER_DIR}/klippy/extras"
SCAFFOLD="${EXTRAS_DIR}/cartographer.py"
SCAFFOLD_CACHE="${PKG_PARENT}/.cartographer-scaffold.py"   # persistent copy
PYTHON="/usr/share/klippy-env/bin/python3"
CONFIG_DIR="/usr/data/printer_data/config"
INITD="/usr/apps/etc/init.d"
WSSHIM_DIR="/usr/data/wsshim"
FLUIDD_DIR="/usr/data/fluidd"

# config files this setup includes from printer.cfg
CFG_FILES="cartographer.cfg cartographer_macros.cfg safe_wipe.cfg"
# printer.cfg include/section lines the live setup relies on
INCLUDE_LINES="[carto_prtouch_shim]
[include cartographer.cfg]
[include cartographer_macros.cfg]
[include safe_wipe.cfg]"

log()  { echo "[*] $*"; }
ok()   { echo "[+] $*"; }
warn() { echo "[!] $*"; }
die()  { echo "[-] $*" >&2; exit 1; }

# ---------------------------------------------------------------- checks --
preflight() {
  [ "$(id -u)" -eq 0 ] || die "must run as root"
  [ -x "$PYTHON" ]      || die "klippy python not found at $PYTHON"
  [ -d "$EXTRAS_DIR" ]  || die "klipper extras not found at $EXTRAS_DIR (is klippy installed / mounted?)"
  touch "${EXTRAS_DIR}/.wtest" 2>/dev/null || die "extras dir is read-only: $EXTRAS_DIR (nothing to re-lay onto)"
  rm -f "${EXTRAS_DIR}/.wtest"
  [ -d "$LIB_DIR" ] || die "persistent plugin missing at $LIB_DIR — run 'sh install.sh' first (needs internet)"
  ok "preflight ok (root, klippy extras writable, persistent plugin present)"
}

# -------------------------------------------------- 1. scaffold (extras) --
relay_scaffold() {
  # The scaffold carries two runtime patches (prior-trigger guard + scan
  # trigger temperature fix). It is generated by install.sh. We keep a
  # persistent cache so a re-seed can be repaired with no internet.
  if [ -f "$SCAFFOLD" ] && [ ! -f "$SCAFFOLD_CACHE" ]; then
    cp "$SCAFFOLD" "$SCAFFOLD_CACHE"
    ok "cached current scaffold -> $SCAFFOLD_CACHE"
  fi
  if [ ! -f "$SCAFFOLD" ]; then
    [ -f "$SCAFFOLD_CACHE" ] || die "no scaffold at $SCAFFOLD and no cache at $SCAFFOLD_CACHE — run 'sh install.sh' once (needs internet)"
    cp "$SCAFFOLD_CACHE" "$SCAFFOLD"
    log "restored scaffold from cache"
  fi
  chmod 644 "$SCAFFOLD"                     # klippy runs as 'creality' — must be world-readable
  ok "scaffold in place -> $SCAFFOLD"
}

# ----------------------------------------------- 2. custom klippy extras --
relay_extras() {
  src="${SCRIPT_DIR}/extras"
  for f in carto_prtouch_shim.py carto_shell_command.py; do
    [ -f "${src}/${f}" ] || { warn "missing ${src}/${f} — skipped"; continue; }
    cp "${src}/${f}" "${EXTRAS_DIR}/${f}"
    chmod 644 "${EXTRAS_DIR}/${f}"
    ok "extra -> ${EXTRAS_DIR}/${f}"
  done
  # ensure the whole persistent package tree is traversable/readable by 'creality'
  chmod 755 "$PKG_PARENT" "$LIB_DIR" 2>/dev/null || true
  chmod -R a+rX "$PKG_PARENT" 2>/dev/null || true
}

# ---------------------------------------------------- 3. boot hooks -------
relay_initd() {
  # Only re-lay a hook if its persistent payload actually survived in /usr/data.
  if [ -d "$WSSHIM_DIR" ] && [ -f "${SCRIPT_DIR}/wsshim/S97dbshim" ]; then
    cp "${SCRIPT_DIR}/wsshim/S97dbshim" "${INITD}/S97dbshim"
    chmod 755 "${INITD}/S97dbshim"
    ok "boot hook -> ${INITD}/S97dbshim"
    "${INITD}/S97dbshim" restart >/dev/null 2>&1 && ok "dbshim restarted" || warn "dbshim restart returned nonzero"
  else
    log "wsshim not installed in /usr/data — skipping S97dbshim"
  fi
  if [ -d "$FLUIDD_DIR" ] && [ -f "${SCRIPT_DIR}/fluidd/S98fluidd" ]; then
    cp "${SCRIPT_DIR}/fluidd/S98fluidd" "${INITD}/S98fluidd"
    chmod 755 "${INITD}/S98fluidd"
    ok "boot hook -> ${INITD}/S98fluidd"
    "${INITD}/S98fluidd" restart >/dev/null 2>&1 && ok "fluidd restarted" || warn "fluidd restart returned nonzero"
  else
    log "fluidd not installed in /usr/data — skipping S98fluidd"
  fi
}

# ------------------------------------------------ 4. config files ---------
relay_configs() {
  [ -d "$CONFIG_DIR" ] || { warn "config dir $CONFIG_DIR missing — skipping config stage"; return 0; }
  for f in $CFG_FILES; do
    if [ -f "${CONFIG_DIR}/${f}" ]; then
      log "kept existing ${f} (not overwriting — may hold your calibration)"
      continue
    fi
    # search repo config/ then the captured live copy alongside the repo
    for cand in "${SCRIPT_DIR}/config/${f}" "${SCRIPT_DIR}/../analysis/live_k1c/${f}"; do
      [ -f "$cand" ] || continue
      cp "$cand" "${CONFIG_DIR}/${f}"
      chmod 644 "${CONFIG_DIR}/${f}"
      ok "config -> ${CONFIG_DIR}/${f}  (from ${cand})"
      break
    done
    [ -f "${CONFIG_DIR}/${f}" ] || warn "no source found for ${f} — supply it in config/ and re-run"
  done
}

# ------------------------- 5. printer.cfg includes (idempotent, backed up) --
ensure_includes() {
  pc="${CONFIG_DIR}/printer.cfg"
  [ -f "$pc" ] || { warn "no printer.cfg at $pc — add the includes yourself once it exists"; return 0; }
  missing=""
  # what to check for (strip to the section/include token)
  for line in "[carto_prtouch_shim]" "[include cartographer.cfg]" "[include cartographer_macros.cfg]" "[include safe_wipe.cfg]"; do
    grep -qF "$line" "$pc" || missing="${missing}${line}\n"
  done
  if [ -z "$missing" ]; then
    ok "printer.cfg already has all include lines"
    return 0
  fi
  stamp="$(date +%Y%m%d_%H%M%S)"
  cp "$pc" "${pc}.bak-reapply-${stamp}"
  ok "printer.cfg backed up -> printer.cfg.bak-reapply-${stamp}"
  # append missing includes ABOVE the SAVE_CONFIG block if present, else at EOF
  if grep -qF "#*#" "$pc"; then
    warn "printer.cfg has a SAVE_CONFIG block; appending includes at EOF is unsafe."
    warn "add these lines by hand ABOVE the '#*# <---' marker:"
    printf "%b" "$missing" | sed 's/^/      /'
  else
    { echo ""; printf "%b" "$missing"; } >> "$pc"
    ok "added missing include lines to printer.cfg:"
    printf "%b" "$missing" | sed 's/^/      /'
  fi
}

# ------------------------------------------------------- 6. verify --------
verify() {
  log "verifying import chain against Creality's klippy"
  ( cd "${KLIPPER_DIR}/klippy" && "$PYTHON" -c "
import sys
sys.path.insert(0,'${LIB_DIR}'); sys.path.insert(0,'.')
import cartographer, cartographer.extra
assert hasattr(cartographer.extra,'load_config')
print('    cartographer', cartographer.__version__, 'load_config OK')
" ) 2>/dev/null && ok "import chain verified" || warn "import verification failed — check klippy.log after restart"
}

# ------------------------------------------------ 7. restart klipper ------
restart_klipper() {
  for svc in /usr/apps/etc/init.d/S*klipper* /etc/init.d/S*klipper*; do
    [ -x "$svc" ] || continue
    "$svc" restart >/dev/null 2>&1 && { ok "restarted $(basename "$svc")"; return 0; }
  done
  warn "could not find a klipper init script — restart Klipper from Fluidd/Moonraker instead"
}

# ------------------------------------------------------------------ main --
case "${1:-}" in
  --help|-h)
    echo "usage: $0            # re-lay /usr/apps files after a firmware update/re-seed (offline)"
    echo "       $0 --help"
    echo ""
    echo "First-time setup (needs internet) is still: sh install.sh"
    exit 0 ;;
  "")
    log "reapply: restoring live Cartographer setup from ${SCRIPT_DIR}"
    preflight
    relay_scaffold
    relay_extras
    relay_initd
    relay_configs
    ensure_includes
    verify
    restart_klipper
    echo ""
    ok  "done. If a print looks off, re-run calibration (heat-soaked bed):"
    echo "      CARTOGRAPHER_TOUCH_CALIBRATE ; CARTOGRAPHER_SCAN_CALIBRATE ; BED_MESH_CALIBRATE"
    ;;
  *) die "unknown option: $1  (try --help)" ;;
esac
